import { BehavioralRule, SystemSettings } from '../types/models.ts';

export const ANTI_PROCRASTINATION_RULES: BehavioralRule[] = [
  {
    ruleNumber: 1,
    code: 'RULE 01',
    name: 'Start before motivation.',
    title: 'Start before motivation.',
    principle: 'Do not wait for motivation. Start with the first physical action.',
    explanation: 'Motivation is an emotional state that follows physical engagement; it is not a prerequisite for initiating work. Waiting to feel ready surrenders control to immediate comfort-seeking.',
    whyStartUsesIt: 'Lowers activation energy to a nearly zero-resistance physical threshold (<10 seconds), preventing the amygdala from triggering avoidance.',
    practicalExample: 'Instead of waiting to feel inspired to write a report: open the text document, type the title line, and write the first incomplete sentence.',
    contextTag: 'starting',
  },
  {
    ruleNumber: 2,
    code: 'RULE 02',
    name: 'Define a concrete output.',
    title: 'Define a concrete output.',
    principle: 'Every scheduled session must produce a tangible, verifiable artifact.',
    explanation: 'The cognitive system interprets undefined tasks as boundless effort and flees into low-friction distractions. A concrete output creates a visible finish line.',
    whyStartUsesIt: 'Closes the ambiguity loophole. Knowing exactly what physical artifact will exist allows the brain to calculate a bounded expenditure of energy.',
    practicalExample: 'Replace "Work on thesis" with "Write 300 words for the methodology section and export draft to PDF".',
    contextTag: 'planning',
  },
  {
    ruleNumber: 3,
    code: 'RULE 03',
    name: 'Define the first physical action.',
    title: 'Define the first physical action.',
    principle: 'Convert abstract goals into a concrete bodily movement.',
    explanation: 'Executive dysfunction peaks when a task requires multiple unsequenced decisions before starting. Defining the exact physical gesture eliminates startup paralysis.',
    whyStartUsesIt: 'Bypasses conceptual decision fatigue. The nervous system only has to execute one physical command rather than solve the entire project.',
    practicalExample: 'Replace "Study linear algebra" with "Open notebook to page 42, pick up blue pen, and write down Problem 1".',
    contextTag: 'starting',
  },
  {
    ruleNumber: 4,
    code: 'RULE 04',
    name: 'Define the next slot before leaving the current slot.',
    title: 'Define the next slot before leaving the current slot.',
    principle: 'Lock in tomorrow or the next session while your mental cache is hot.',
    explanation: 'The friction of starting is highest when returning to a cold task with zero pre-loaded context. Pre-defining the next step eliminates restart hesitation.',
    whyStartUsesIt: 'Preserves cognitive continuity. Leaving a clear runway ensures you never sit down to a blank calendar wondering what to do next.',
    practicalExample: 'Before closing your IDE at the end of a session, write down the exact file name and first test you will run when you sit down tomorrow at 09:30.',
    contextTag: 'planning',
  },
  {
    ruleNumber: 5,
    code: 'RULE 05',
    name: 'Keep the phone physically away during focused work.',
    title: 'Keep the phone physically away during focused work.',
    principle: 'Physical distance outperforms mental willpower every time.',
    explanation: 'Even when silent and face-down, a smartphone within physical arm reach taxes working memory by requiring continuous unconscious inhibition.',
    whyStartUsesIt: 'Environmental architecture eliminates micro-distractions. Placing the phone in another room or out of arm reach removes the zero-effort dopamine escape route.',
    practicalExample: 'Put your phone in another room or in a zippered bag across the room before pressing Start on your 45-minute focus session.',
    contextTag: 'environment',
  },
  {
    ruleNumber: 6,
    code: 'RULE 06',
    name: 'Capture distractions instead of following them.',
    title: 'Capture distractions instead of following them.',
    principle: 'Acknowledge internal impulses, park them external to your brain, and return to work.',
    explanation: 'Trying to suppress an intrusive impulse ("I need to check that email") causes cognitive rebound. Writing it down discharges the urgency without derailing focus.',
    whyStartUsesIt: 'Validates the urge without obeying it. Externalizing the thought clears executive RAM and immediately restores single-task attention.',
    practicalExample: 'When an urge strikes to look up flight prices, press "I\'m distracted", select "Unrelated task", note "Check flight prices at 18:00", and instantly return to code.',
    contextTag: 'execution',
  },
  {
    ruleNumber: 7,
    code: 'RULE 07',
    name: 'Use 10-minute recovery after a missed slot.',
    title: 'Use 10-minute recovery after a missed slot.',
    principle: 'Never let a missed window collapse the remainder of the day.',
    explanation: 'Missing a planned slot triggers shame and the "what-the-hell" effect, leading to total day abandonment. A 10-minute micro-start breaks the guilt spiral immediately.',
    whyStartUsesIt: 'Preserves behavioral momentum. Procrastination is maintained by guilt-driven postponement; a micro-session proves you can re-engage without perfectionism.',
    practicalExample: 'You missed your 14:00 session by an hour. Instead of abandoning the day, click "Recover in 10 minutes" and commit to working on one single paragraph.',
    contextTag: 'recovery',
  },
  {
    ruleNumber: 8,
    code: 'RULE 08',
    name: 'Measure outputs and behavior.',
    title: 'Measure outputs and behavior.',
    principle: 'Track tangible artifacts delivered and startup latency, never passive hours.',
    explanation: 'Logging raw desk time incentivizes pseudo-work, web surfing, and passive reading. Genuine anti-procrastination measures visible output and starting friction.',
    whyStartUsesIt: 'Prevents self-deception. When you measure what was produced and how fast you started, vanity metrics vanish and real capability compounds.',
    practicalExample: 'Record "Derived fundamental matrix and drafted 4 test assertions", never "Spent 3 hours studying vision".',
    contextTag: 'execution',
  },
  {
    ruleNumber: 9,
    code: 'RULE 09',
    name: 'Separate drafting from polishing.',
    title: 'Separate drafting from polishing.',
    principle: 'Create with judgment turned off; edit with critical faculty turned on.',
    explanation: 'Attempting to generate high-quality work while simultaneously critiquing every sentence creates immediate cognitive gridlock and perfectionistic paralysis.',
    whyStartUsesIt: 'Destroys perfectionism at the root. Separating the creation phase from the editing phase allows rapid volume generation without self-censorship.',
    practicalExample: 'In a 40-minute drafting slot, write continuously without hitting backspace or re-reading previous paragraphs. Schedule a separate slot tomorrow for proofreading.',
    contextTag: 'starting',
  },
  {
    ruleNumber: 10,
    code: 'RULE 10',
    name: 'Plan tomorrow at night.',
    title: 'Plan tomorrow at night.',
    principle: 'Tomorrow is locked in at night; never negotiated in the morning.',
    explanation: 'Morning willpower is fragile and prone to rationalizing delays. Waking up without a pre-decided Top 1 task invites decision fatigue and immediate phone checking.',
    whyStartUsesIt: 'Pre-commits execution. Waking up to an already configured slot with a pre-defined first action eliminates morning negotiation.',
    practicalExample: 'Complete the 3-minute Night Review before bed: identify tomorrow\'s Top 1 assignment, exact start time (09:00), and first physical action.',
    contextTag: 'night',
  },
];

export const DEFAULT_SETTINGS: SystemSettings = {
  theme: 'dark',
  soundEnabled: true,
  phoneCheckStrict: true,
  workDayStart: '09:00',
  workDayEnd: '18:00',
  notificationsEnabled: true,
  notificationCategories: {
    upcomingSlot: true,
    nextActionReady: true,
    missedSlotRecovery: true,
    nightReview: true,
    nightReviewTime: '21:00',
  },
};
